language: java
sudo: false
install: true
addons:
   sonarcloud:
      organization: "madewithpaper-github"
      token:
         secure: ab1ff99dd31de531f29948ddfa98c012fe0c17fc

jdk:
   - oraclejdk8
script:
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization={madewithpaper-github} -Dsonar.login={176699fe6782b4df9a500d994cfb0b00aec3e033} -Dsonar.branch={Master}
cache:
   directories:
   - '$HOME/.m2/repository'
   - '$HOME/.sonar/cache'
